Algoritmo "Q1"
// Disciplina  : 
// Professor   :
// Descrição   :
// Autor(a)    : graciele selma da silva
// Data atual  : 
Var
   a, b : Inteiro
Inicio

escreva("Digite o primeiro valor: ")
leia(a)

escreva("Digite o segundo valor: ")
leia(b)


escreval("Valor da soma e ", (a+b))
escreval("Valor da subtrção e ", (a-b))
escreval("Valor da multiplicação e ", (a*b))
escreval("Valor da divisão e ", (a/b))

Fimalgoritmo