Algoritmo "Q1"
// Disciplina  : 
// Professor   :
// Descrição   :
// Autor(a)    : graciele selma da silva
// Data atual  : 
Var
   nota1,nota2,nota3, media :real
Inicio

escreva ("digite a primeira numero:")
leia(nota1)

escreva("digite a segunda numero:")
leia (nota2)

escreva("digite a terceira numero:")
leia (nota3)

media <- (nota1 + nota2 + nota3 ) / 3


escreval("A Media e: ",media)


Fimalgoritmo